Load Dataset

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Netflix.csv", encoding="latin-1")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Understanding Data

In [2]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   object
 1   type          8809 non-null   object
 2   title         8809 non-null   object
 3   director      6175 non-null   object
 4   cast          7984 non-null   object
 5   country       7978 non-null   object
 6   date_added    8799 non-null   object
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   object
 9   duration      8806 non-null   object
 10  listed_in     8809 non-null   object
 11  description   8809 non-null   object
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
 14  Unnamed: 14   0 non-null      float64
 15  Unnamed: 15   0 non-null      float64
 16  Unnamed: 16   0 non-null      float64
 17  Unnamed: 17   0 non-null      float64
 18  Unnamed: 18   0 non-null      float64
 19  Unnamed: 19   0 non-null      float64
 20  Unnamed: 20   0 non-null      float64
 21  Unnamed: 21   0 non-null      float64
 22  Unnamed: 22   0 non-null      float64
 23  Unnamed: 23   0 non-null      float64
 24  Unnamed: 24   0 non-null      float64
 25  Unnamed: 25   0 non-null      float64
dtypes: float64(14), int64(1), object(11)
memory usage: 1.7+ MB

Drop Unnecessary Columns

In [3]:
# Drop empty unnamed columns
df = df.loc[:, ~df.columns.str.contains('Unnamed')]
df.shape

(8809, 12)

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df_clean = df.copy()

In [6]:
print(df_clean.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

Check Missing Values

In [7]:
df_clean.isna().sum().sort_values(ascending=False)

director        2634
country          831
cast             825
date_added        10
rating             4
duration           3
show_id            0
type               0
title              0
release_year       0
listed_in          0
description        0
dtype: int64

Handling Missing Values

In [8]:
# Handle missing values
for col in ['director', 'cast', 'country', 'rating', 'duration']:
    df_clean[col] = df_clean[col].fillna('Unknown')

df_clean.isna().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

Checking Duplicate Values

In [9]:
print("Total rows:", len(df_clean))
print("Exact Duplicate rows:", df_clean.duplicated().sum())
print("Logical Duplicate rows:", df_clean.duplicated(subset=['title'], keep=False).sum())

Total rows: 8809
Exact Duplicate rows: 0
Logical Duplicate rows: 6

In [10]:
df_clean[df_clean.duplicated(subset=['title'], keep=False)].sort_values('title')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3962,s3963,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
5966,s5967,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
4522,s4523,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Ãigarden, Jonas Str...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
5965,s5966,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Ãigarden, Jonas Str...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
3996,s3997,TV Show,Feb-09,Unknown,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",Unknown,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."
5964,s5965,TV Show,Feb-09,Unknown,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",Unknown,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."

Handling Duplicate Values

In [11]:
df_clean = df_clean.drop_duplicates(subset=['title'], keep='first')

In [12]:
print("Logical Duplicate rows:", df_clean.duplicated(subset=['title'], keep=False).sum())

Logical Duplicate rows: 0

In [13]:
df_clean.shape

(8806, 12)

Checking Invalid Values

In [14]:
for col in df_clean.columns:
    print(f"\n{col}")
    print(df_clean[col].value_counts(dropna=False).head(5))

show_id
show_id
s8809    1
s1       1
s2       1
s3       1
s4       1
Name: count, dtype: int64

type
type
Movie      6130
TV Show    2676
Name: count, dtype: int64

title
title
Serena                   1
Dick Johnson Is Dead     1
Blood & Water            1
Ganglands                1
Jailbirds New Orleans    1
Name: count, dtype: int64

director
director
Unknown                    2633
Rajiv Chilaka                19
RaÃºl Campos, Jan Suter      18
Marcus Raboy                 16
Suhas Kadav                  16
Name: count, dtype: int64

cast
cast
Unknown                                                                                    825
David Attenborough                                                                          19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil     14
Samuel West                                                                                 10
Jeff Dunham                                                                                  7
Name: count, dtype: int64

country
country
United States     2819
India              971
Unknown            830
United Kingdom     419
Japan              245
Name: count, dtype: int64

date_added
date_added
January 1, 2020      109
November 1, 2019      89
March 1, 2018         75
December 31, 2019     74
October 1, 2018       71
Name: count, dtype: int64

release_year
release_year
2018    1145
2017    1032
2019    1029
2020     953
2016     902
Name: count, dtype: int64

rating
rating
TV-MA    3208
TV-14    2158
TV-PG     863
R         798
PG-13     490
Name: count, dtype: int64

duration
duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
Name: count, dtype: int64

listed_in
listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Name: count, dtype: int64

description
description
Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think.    4
A surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 3
Multiple women report their husbands as missing but when it appears they are looking for the same man, a police officer traces their cryptic connection.     3
Challenged to compose 100 songs before he can marry the girl he loves, a tortured but passionate singer-songwriter embarks on a poignant musical journey.    3
This educational series for tiny tots features a toe-tapping spin on nursery rhymes with upbeat tunes and a diverse set of easy-to-follow lessons.           2
Name: count, dtype: int64

In [15]:
print(df_clean['rating'].value_counts(dropna=False).head(25))

rating
TV-MA       3208
TV-14       2158
TV-PG        863
R            798
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
Unknown        4
NC-17          3
UR             3
66 min         1
84 min         1
74 min         1
A              1
Name: count, dtype: int64

In [16]:
valid_ratings = [
    "TV-MA", "TV-14", "TV-PG", "R", "PG-13",
    "TV-Y7", "TV-Y", "PG", "TV-G", "G",
    "TV-Y7-FV", "NC-17"
]

df_clean = df_clean[df_clean['rating'].isin(valid_ratings)]

In [17]:
df_clean = df_clean[~df_clean['title'].str.match(r'\d{1,2}-[A-Za-z]{3}', na=False)]

In [18]:
df_clean['country'] = df_clean['country'].fillna("Unknown")

Feature Engineering

In [19]:
# Parse dates
df_clean['date_added'] = pd.to_datetime(df_clean['date_added'], errors='coerce')

# Feature engineering
df_clean['year_added'] = df_clean['date_added'].dt.year
df_clean['month_added'] = df_clean['date_added'].dt.month
df_clean['month_name'] = df_clean['date_added'].dt.month_name()
df_clean['duration_num'] = df_clean['duration'].str.extract(r'(\d+)').astype(float)
df_clean['main_genre'] = df_clean['listed_in'].str.split(',').str[0]
df_clean['main_country'] = df_clean['country'].fillna('Unknown').str.split(',').str[0]

In [20]:
df_clean = df_clean[(df_clean['year_added'] < 2024) | df_clean['year_added'].isna()]

In [21]:
df_clean.shape

(8712, 18)

In [22]:
df_clean.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'year_added', 'month_added', 'month_name', 'duration_num', 'main_genre',
       'main_country'],
      dtype='object')

In [23]:
print("Original:", len(df))
print("Cleaned:", len(df_clean))
print("Removed:", len(df) - len(df_clean))

Original: 8809
Cleaned: 8712
Removed: 97

Save Cleaned Dataset

In [24]:
df_clean.to_csv("Netflix_Cleaned_Dataset.csv", index=False)

In [25]:
df_clean.to_excel("Netflix_Cleaned_Dataset.xlsx", index=False)